/*******************************************************************************
 * Copyright (c) 2000, 2015 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.wst.jsdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.wst.jsdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameWHITESPACE = 1000,
		TokenNameCOMMENT_LINE = 1001,
		TokenNameCOMMENT_BLOCK = 1002,
		TokenNameCOMMENT_JAVADOC = 1003,
		TokenNameSHEBANG_LINE = 1004,
		TokenNameUNKNOWN = 1005;

    public final static int
    TokenNameIdentifier = 32,
    TokenNameabstract = 90,
    TokenNameawait = 91,
    TokenNameboolean = 92,
    TokenNamebreak = 61,
    TokenNamebyte = 93,
    TokenNamecase = 86,
    TokenNamecatch = 88,
    TokenNamechar = 94,
    TokenNameclass = 95,
    TokenNamecontinue = 62,
    TokenNameconst = 57,
    TokenNamedefault = 87,
    TokenNamedebugger = 63,
    TokenNamedelete = 47,
    TokenNamedo = 64,
    TokenNamedouble = 96,
    TokenNameelse = 74,
    TokenNameenum = 97,
    TokenNameexport = 98,
    TokenNameextends = 99,
    TokenNamefalse = 36,
    TokenNamefinal = 100,
    TokenNamefinally = 89,
    TokenNamefloat = 101,
    TokenNamefor = 65,
    TokenNamefunction = 55,
    TokenNamegoto = 102,
    TokenNameif = 66,
    TokenNamein = 26,
    TokenNameimplements = 103,
    TokenNameimport = 104,
    TokenNameinstanceof = 13,
    TokenNameint = 105,
    TokenNameinterface = 106,
    TokenNamelet = 58,
    TokenNamelong = 107,
    TokenNamenative = 108,
    TokenNamenew = 37,
    TokenNamenull = 38,
    TokenNamepackage = 109,
    TokenNameprivate = 110,
    TokenNameprotected = 111,
    TokenNamepublic = 112,
    TokenNamereturn = 67,
    TokenNameshort = 113,
    TokenNamestatic = 114,
    TokenNamesuper = 115,
    TokenNameswitch = 68,
    TokenNamesynchronized = 116,
    TokenNamethis = 39,
    TokenNamethrow = 69,
    TokenNamethrows = 117,
    TokenNametransient = 118,
    TokenNametrue = 40,
    TokenNametry = 70,
    TokenNametypeof = 48,
    TokenNameundefined = 41,
    TokenNamevar = 59,
    TokenNamevoid = 49,
    TokenNamevolatile = 119,
    TokenNamewhile = 60,
    TokenNamewith = 71,
    TokenNameyield = 120,
    TokenNameIntegerLiteral = 33,
    TokenNameLongLiteral = 42,
    TokenNameFloatingPointLiteral = 43,
    TokenNameDoubleLiteral = 44,
    TokenNameCharacterLiteral = 34,
    TokenNameStringLiteral = 35,
    TokenNameRegExLiteral = 45,
    TokenNamePLUS_PLUS = 3,
    TokenNameMINUS_MINUS = 4,
    TokenNameEQUAL_EQUAL = 18,
    TokenNameEQUAL_EQUAL_EQUAL = 19,
    TokenNameNOT_EQUAL_EQUAL = 20,
    TokenNameLESS_EQUAL = 14,
    TokenNameGREATER_EQUAL = 15,
    TokenNameNOT_EQUAL = 21,
    TokenNameLEFT_SHIFT = 6,
    TokenNameRIGHT_SHIFT = 7,
    TokenNameUNSIGNED_RIGHT_SHIFT = 5,
    TokenNamePLUS_EQUAL = 75,
    TokenNameMINUS_EQUAL = 76,
    TokenNameMULTIPLY_EQUAL = 77,
    TokenNameDIVIDE_EQUAL = 78,
    TokenNameAND_EQUAL = 79,
    TokenNameOR_EQUAL = 80,
    TokenNameXOR_EQUAL = 81,
    TokenNameREMAINDER_EQUAL = 82,
    TokenNameLEFT_SHIFT_EQUAL = 83,
    TokenNameRIGHT_SHIFT_EQUAL = 84,
    TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 85,
    TokenNameOR_OR = 29,
    TokenNameAND_AND = 28,
    TokenNamePLUS = 1,
    TokenNameMINUS = 2,
    TokenNameNOT = 50,
    TokenNameREMAINDER = 9,
    TokenNameXOR = 23,
    TokenNameAND = 22,
    TokenNameMULTIPLY = 10,
    TokenNameOR = 27,
    TokenNameTWIDDLE = 46,
    TokenNameDIVIDE = 11,
    TokenNameGREATER = 16,
    TokenNameLESS = 17,
    TokenNameLPAREN = 8,
    TokenNameRPAREN = 52,
    TokenNameLBRACE = 51,
    TokenNameRBRACE = 56,
    TokenNameLBRACKET = 12,
    TokenNameRBRACKET = 54,
    TokenNameSEMICOLON = 25,
    TokenNameQUESTION = 30,
    TokenNameCOLON = 53,
    TokenNameCOMMA = 24,
    TokenNameDOT = 31,
    TokenNameEQUAL = 73,
    TokenNameARROW = 121,
    TokenNameEOF = 72,
    TokenNameERROR = 122;
	
}
